# $NetBSD$

.include "../Makefile.inc"

.PATH:	${S}/secmodel/cell

KMOD=	secmodel_cell
SRCS=	secmodel_cell.c \
	secmodel_cell_module.c \
	secmodel_cell_policy.c \
	secmodel_cell_sysctl.c

.include <bsd.kmodule.mk>
