#	$NetBSD$
#
# /etc/cells/defaults.conf -- defaults for celladm(8)
#
# root_base must be an absolute path to a prepared readonly base root.
# Example:
# root_base=/var/cells/base/11.0-amd64
#
root_base=
local_dev=yes
